"""initial setup

Revision ID: 73a80f892cef
Revises: 
Create Date: 2019-07-03 22:40:15.504020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73a80f892cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vrdgbyloc',
    sa.Column('Sensor', sa.NullType(), nullable=False),
    sa.Column('SensorOption', sa.NullType(), nullable=False),
    sa.Column('SensorType', sa.NullType(), nullable=True),
    sa.Column('Location', sa.NullType(), nullable=True),
    sa.Column('Sector', sa.NullType(), nullable=True),
    sa.Column('Readings', sa.NullType(), nullable=True),
    sa.Column('Minr', sa.NullType(), nullable=True),
    sa.Column('Maxr', sa.NullType(), nullable=True),
    sa.Column('Avgr', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('Sensor', 'SensorOption')
    )
    op.create_table('vrdgbysector',
    sa.Column('Sector', sa.NullType(), nullable=False),
    sa.Column('S_Type', sa.NullType(), nullable=False),
    sa.Column('SensorOption', sa.NullType(), nullable=False),
    sa.Column('SensorType', sa.NullType(), nullable=True),
    sa.Column('Readings', sa.NullType(), nullable=True),
    sa.Column('Minr', sa.NullType(), nullable=True),
    sa.Column('Maxr', sa.NullType(), nullable=True),
    sa.Column('Avgr', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('Sector', 'S_Type', 'SensorOption')
    )
    op.create_table('vreadingspivot',
    sa.Column('Controller', sa.NullType(), nullable=False),
    sa.Column('rdate', sa.NullType(), nullable=False),
    sa.Column('rhour', sa.NullType(), nullable=False),
    sa.Column('Location', sa.NullType(), nullable=True),
    sa.Column('Sector', sa.NullType(), nullable=True),
    sa.Column('DO_MG', sa.NullType(), nullable=True),
    sa.Column('DO_PS', sa.NullType(), nullable=True),
    sa.Column('EC_S', sa.NullType(), nullable=True),
    sa.Column('EC_EC', sa.NullType(), nullable=True),
    sa.Column('EC_SG', sa.NullType(), nullable=True),
    sa.Column('T_C', sa.NullType(), nullable=True),
    sa.Column('T_F', sa.NullType(), nullable=True),
    sa.Column('WL_US', sa.NullType(), nullable=True),
    sa.Column('WL_PS', sa.NullType(), nullable=True),
    sa.Column('pH', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('Controller', 'rdate', 'rhour')
    )
    op.drop_index('name', table_name='group')
    op.drop_table('group')
    op.drop_table_comment(
        'controller_version',
        existing_comment='Versions and version details for controllers',
        schema=None
    )
    op.drop_constraint('ctlconfig_ibfk_2', 'ctlconfig', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'sector', ['Sector'], ['id'])
    op.drop_column('location', 'notification')
    op.alter_column('log_ctrl', 'controller',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('log_ctrl', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('log_ctrl', 'errortime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('log_ctrl', 'sensor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'log_ctrl', 'controller', ['controller'], ['id'])
    op.create_foreign_key(None, 'log_ctrl', 'sensor', ['sensor'], ['id'])
    op.drop_table_comment(
        'log_ctrl',
        existing_comment='	',
        schema=None
    )
    op.alter_column('paramrange', 'maxOfflineAuto',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='maximum length of time in minutes controller does not send data before it becomes an alert, for automated tanks',
               existing_nullable=True,
               existing_server_default=sa.text("'30'"))
    op.alter_column('paramrange', 'maxOfflineManual',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='maximum length of time in minutes controller does not send data before it becomes an alert, for manual tanks',
               existing_nullable=True,
               existing_server_default=sa.text("'120'"))
    op.drop_table_comment(
        'paramrange',
        existing_comment='Definition of valid parameter values per sector',
        schema=None
    )
    op.alter_column('sensor', 'SerialNo',
               existing_type=mysql.VARCHAR(length=45),
               comment=None,
               existing_comment='The hardware number using which controller interfaces with the sensor. For I2C, can be I2C address',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'SerialNo',
               existing_type=mysql.VARCHAR(length=45),
               comment='The hardware number using which controller interfaces with the sensor. For I2C, can be I2C address',
               existing_nullable=True)
    op.create_table_comment(
        'paramrange',
        'Definition of valid parameter values per sector',
        existing_comment=None,
        schema=None
    )
    op.alter_column('paramrange', 'maxOfflineManual',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='maximum length of time in minutes controller does not send data before it becomes an alert, for manual tanks',
               existing_nullable=True,
               existing_server_default=sa.text("'120'"))
    op.alter_column('paramrange', 'maxOfflineAuto',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='maximum length of time in minutes controller does not send data before it becomes an alert, for automated tanks',
               existing_nullable=True,
               existing_server_default=sa.text("'30'"))
    op.create_table_comment(
        'log_ctrl',
        '	',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'log_ctrl', type_='foreignkey')
    op.drop_constraint(None, 'log_ctrl', type_='foreignkey')
    op.alter_column('log_ctrl', 'sensor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('log_ctrl', 'errortime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('log_ctrl', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('log_ctrl', 'controller',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('location', sa.Column('notification', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('ctlconfig_ibfk_2', 'ctlconfig', 'componenttype', ['Component_Type'], ['id'])
    op.create_table_comment(
        'controller_version',
        'Versions and version details for controllers',
        existing_comment=None,
        schema=None
    )
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'group', ['name'], unique=True)
    op.drop_table('vreadingspivot')
    op.drop_table('vrdgbysector')
    op.drop_table('vrdgbyloc')
    # ### end Alembic commands ###
